version: '3.8'
services:
  frontend:
    build:
      context: ../client
    ports:
      - "8080:80"

  backend:
    build:
      context: ../server
    ports:
      - "3000:3000"
    network_mode: "host"
    depends_on:
      - database
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

  database:
    image: postgres:14
    container_name: database
    ports:
      - "5432:5432"
    network_mode: "host"
    env_file:
      - ../.env
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - database:/var/lib/postgresql/data
    restart: always

volumes:
  database:
